name: Java CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Compilar el proyecto
        run: |
          mkdir -p out
          javac -d out $(find src/main/java -name "*.java")

      - name: Ejecutar la aplicación (prueba)
        run: java -cp out com.jpmonroy.app.Main
        continue-on-error: true
